server.port=8080

spring.datasource.url=${postgresql://postgres:luvSRylWodOxxfJZZjnxRRrjCKdJEPbi@postgres.railway.internal:5432/railway}
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.datasource.url=${postgresql://postgres:luvSRylWodOxxfJZZjnxRRrjCKdJEPbi@postgres.railway.internal:5432/railway}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
