server.port=8080

spring.datasource.url=${postgresql://postgres:luvSRylWodOxxfJZZjnxRRrjCKdJEPbi@postgres.railway.internal:5432/railway}
spring.datasource.username=postgres
spring.datasource.password=luvSRylWodOxxfJZZjnxRRrjCKdJEPbi
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
